name: base
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
- bcftools<=1.18
- bedtools<=2.31.0
- bzip2<=1.0.8
- pbaa<=1.0.3
- pbmm2<=1.13.0
- pip
- samtools<=1.18
- seqkit<=2.5.1
- seqtk<=1.4